---
- name: detected rails package
  shell: bash -lc "rails -v | grep {{ rails_version }}"
  register: rails_installed
  ignore_errors: yes
  changed_when: false
  tags: rails

- name: install rails package
  command: bash -lc "gem install rails -v {{ rails_version }}"
  when: rails_installed is failed
  tags: rails
