---
- name: detected passenger module
  shell: bash -lc "passenger -v | grep {{ passenger_version }}"
  register: passenger_installed
  ignore_errors: yes
  changed_when: false
  tags: passenger

- name: install passenger module
  shell: bash -lc "gem install passenger -v {{ passenger_version }}"
  when: passenger_installed is failed
  tags: passenger

- name: install passenger-apache depends packages
  yum:
      name:
          - gcc-c++
          - libcurl-devel
          - httpd-devel
          - apr-devel
          - apr-util-devel
  tags: passenger

- name: install passenger-apache module
  shell: bash -lc "passenger-install-apache2-module --auto --languages=ruby"
  when: passenger_installed is failed
  tags: passenger

- name: setup passenger-apache module
  shell: bash -lc "passenger-install-apache2-module --snippet > /etc/httpd/conf.d/passenger.conf"
  when: passenger_installed is failed
  tags: passenger
