---
- name: update yum repository
  yum:
    name: "*"
    state: latest

- name: install base packages
  yum:
    name:
      - git
      - chrony
      - libselinux-python

- name: disable selinux
  selinux:
    state: disabled

- name: setup timezone
  timezone:
    name: Asia/Tokyo

- name: setup languege 1/2
  lineinfile:
    dest: /etc/locale.conf
    regexp: "^LANG="
    line: 'LANG="ja_JP.UTF-8"'
    backup: yes

- name: setup languege 2/2
  command: localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
  changed_when: false
